### ISSUE TITLE
Leveling up

### ISSUE THREAD

**Issue by Nucliam** [Nucliam/RPG-project#1]

**Comment by Scootzy** [comment]
lvl 1 has 10 exp
lvl 2 has 20 exp
lvl 3 has 30 exp
lvl 4  has 40 exp
lvl 5 has 50 exp
lvl 6 has 60 exp
lvl 7 has 70 exp
lvl 8 has 80 exp
lvl 9 has 90 exp
lvl 10 has 100 exp
lvl 11 has 110 exp
lvl 12 has 120 exp
lvl 13 has 130 exp
lvl 14 has 140 exp
lvl 15 has 150 exp
lvl 16 has 160 exp
as so on and so forth

**Comment by Scootzy** [comment]
no extra exp given when leveling up

**Comment by Nucliam** [comment]
I have instead changed levelling up to +5 per level, to make task completion easier. Along with this, the levelling up system is now completed.
