### ISSUE TITLE
Different tasks

### ISSUE THREAD

**Issue by Nucliam** [Nucliam/RPG-project#5]

**Comment by Nucliam** [comment]
The tasks which give varying experience could be Homework, Study, Work and Exercise. I'm thinking that Exercise could be worth 2 xp initially, Homework 3, Study 4 and Work 5. These figures may change later through the experience modifier, but I think this is a strong base.

**Comment by Scootzy** [comment]
consider different difficulties of tasks and/or time spent on task and reward more or less respectively

**Comment by Nucliam** [comment]
This has been completed, and a spreadsheet also shows the varying experience depending on tasks.
