### ISSUE TITLE
Experience bar graphic

### ISSUE THREAD

**Issue by Nucliam** [Nucliam/RPG-project#7]

**Comment by Scootzy** [comment]
![exp bar 2](https://user-images.githubusercontent.com/41351660/42976984-084070c8-8c08-11e8-98e7-145262543c71.png)
![exp bar 1](https://user-images.githubusercontent.com/41351660/42976985-08742c1a-8c08-11e8-881b-e93ddd67bf4e.png)
![exp bar 3](https://user-images.githubusercontent.com/41351660/42976986-08a5f3da-8c08-11e8-9e45-f3c5fb400306.jpg)

**Comment by Scootzy** [comment]
posible designs influences

**Comment by Nucliam** [comment]
Experience bar and progress code is completed.
