### ISSUE TITLE
Level, Experience and Currency Labels

### ISSUE THREAD

**Issue by Nucliam** [Nucliam/RPG-project#8]

**Comment by Scootzy** [comment]
![currency](https://user-images.githubusercontent.com/41351660/42977126-b4aa39ca-8c08-11e8-8e9a-25a4331b4418.png)

**Comment by Nucliam** [comment]
Level and experience labels are completed.

**Comment by Nucliam** [comment]
All labels are completed, using simple VB "lbl"s. Feel free to open this issue back up and replace them with graphics or something.
